### ISSUE TITLE
Default value about default "sms_coverage" and "ngs_coverage"

### ISSUE THREAD

**Issue by CJ-Chen** [JiaoLaboratory/CRAQ#2]
--sms_coverage|-avgl            Average SMS coverage. Default: 100
        --ngs_coverage|-avgs            Average NGS coverage. Default: 100

Great job, thank you to the development team. I am using this software in my project. I would like to ask if "coverage" here refers to Depth? If so, is the default 100X requirement considered high? Would it be more suitable to lower it to, for example, 30?

**Comment by JiaoLaboratory** [comment]
Hi CJ-Chen,
Thank you for your support of CRAQ. Yes, this parameter represents an estimate of the average sequencing depth. Its idea is primarily used to validate certain regions with extreme high coverage (>5*average depth). Various factors can cause such extreme high coverage, i.e. when our genome is incompletely assembled, those not utilized reads could be forcibly mapped to some similar regions, resulting in a very high coverage of clipping signals（false positive errors).
Based on our experience, this parameter may have a slight impact on the final results. But It's advisable for users to perform a rough estimate about their sequencing depth in advance. If users are uncertain, we recommend this parameter could be a bit higher, because for some small microbial genomes (which usually exhibit high sequencing depth), a setting of 30x might be low.

**Comment by CJ-Chen** [comment]
Thank you for your prompt response.
