### ISSUE TITLE
Can I use ont and HiFi data at the same time?

### ISSUE THREAD

**Issue by Bank-tidy** [JiaoLaboratory/CRAQ#7]
Hello,
Thank you for developing a very useful tool,I have some doubts about using the tool, so I woulld like to ask you for advice:

`$ craq  -g  assembly.fa -sms SMS.fa.gz -ngs NGS_R1.fa.gz,NGS_R2.fa.gz -x map-hifi`
Can I input both of ONT and hifi data at the same time in this step:  -ngs ?

`$ craq  -g assembly.fa -sms SMS_sort.bam -ngs NGS_sort.bam `
Or input  both of the BAM files of ONT and hifi data at the same time in this step:  -ngs ?

**Comment by JiaoLaboratory** [comment]
Sorry, CRAQ cannot take input simultaneously from ONT and HIFI data (.fastq format). Because existing different between ONT and HiFi data.
However, you can merge the BAM files of the two datasets using samtools with the command 'samtools merge SMS_merge.bam HIFI.sort.bam ONT.sort.bam' and then use the merged 'SMS_merge.bam' as input. 
Additionally, the '-ngs' option requires short-reads as input; if you only have HIFI and ONT data, simply execute 'craq -g assembly.fa -sms SMS_merge.bam' is ok."

**Comment by Bank-tidy** [comment]
<img width="447" alt="image" src="https://github.com/JiaoLaboratory/CRAQ/assets/108465040/a67b3565-c19a-45e8-812a-f9088fc17487">

Hello,

Following your suggestion, I merged the BAM files of ONT and HIFI data to generate an image. This process involved sequencing a plant with both second and third-generation techniques. The resulting assembly was performed using ONT and HIFI data. Notably, the third-generation data in the image exhibits fewer errors compared to the second-generation data, which shows more errors. This discrepancy raises questions about the reliability of error correction in the second-generation data. I am seeking your advice on how to interpret these results.

Thank you for your guidance！
